# Generated by Django 3.2.9 on 2021-11-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.URLField(blank=True, null=True, unique=True)),
                ('url', models.TextField(unique=True)),
                ('description', models.TextField(default='NULL')),
            ],
        ),
    ]
