# Generated by Django 4.2.20 on 2025-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("source", models.CharField(max_length=100)),
                ("category", models.CharField(default="General", max_length=100)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
